Add exclude files, exts, paths and add new events
metarhia/metawatch pull request #53
Opened 2023-11-09 18:32 UTC by timursevimli

- [x] tests and linter show no problems (`npm t`)
- [ ] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [ ] description of changes is added in CHANGELOG.md
- [ ] update .d.ts typings

2023-11-14 18:00 UTC, tshemsedinov requested changes
- Please do not drop old events
- Add an issue to deprecate old events before release 2.0
- Remove line in example in readme

2024-01-09 16:52 UTC, timursevimli commented
> * Added issue with canceling old events before version 2.0.

Should I make an issue about this?
Since the old events remain the same as they were with the same contracts, we simply add new ones

2024-01-23 17:57 UTC, tshemsedinov reviewed
- Move `is*` methods out of class
- Rename events to `rmdir`, `delete`

2024-01-26 00:47 UTC, timursevimli commented on test/unit.js
> +metatests.test('Delete file (rm)', (test) => {
Maybe, need update test descriptions like ```Delete: rm``` and ```Delete: rmdir``` ?

2025-06-23 16:49 UTC, closed without merging